// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxbfahumhkguuddrmlfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4YmZhaHVtaGtndXVkZHJtbGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTI5OTIsImV4cCI6MjA3MDcyODk5Mn0.Pgw4338wWXyX-CUEayY4_kYJ7MS0L-oWiLLsAqOo9LI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});